### ISSUE TITLE
probability error

### ISSUE THREAD

**Issue by Boroom** [mcbarlowe/elopy#1]
Hey, thanks for your code but I don't understand something.
When 2 teams with the same elo are playing against each others something isn't clear for me.
When I check the win probability of A (where A is at home) against B I have 0.64. When B is playing against A and B is not at home, I have 0.5 chance to win. But the sum of the two probabilities should be equal to 1. 
Can someone explain me this ?
Thanks!

Code :
`teama = Elo()`
`teamb = Elo()`
`print(teama.win_probs(teamb, is_home=True)) #0.64`
`print(teamb.win_probs(teama, is_home=False)) #0.5`

**Comment by Boroom** [comment]
I found the answer to my question: the probability of winning takes into account the victory and the tie, hence the fact that the sum of the probabilities is not equal to 1.
Source : https://www.reddit.com/r/chess/comments/2y6ezm/how_to_guide_converting_elo_differences_to/

**Comment by Boroom** [comment]
In fact, after several checks and tests I still do not understand. Is my previous solution a good one ?

**Comment by mcbarlowe** [comment]
This is fixed with commit c0f5a5abf17c54a963882150ed9f3dbb293b06b5. Release 0.1.4 has been uploaded to pypi as well with bug fix
